# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f21dd720d8cc3f3de8d7d25ccfb6ef07796389e3a76336597612124dd262d03f80b164670b477ffd8afe7c275aca6a088035c2230ab87649d5990405ecd0ee5c

test:
  secret_key_base: e1c284bcb1d117a8b6fac4cabcf3f6349ec23e81a37a7c117762d317cdf52cf1bc59b77729efb10c882b07f3d0e095808c70edaaa57d7eb3447d1f8f9743b894

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
